name: Pull Request Size Label

on:
  workflow_call:
    inputs:
      sizes:
        description: Sizes configuration
        required: false
        type: string
        default: >
          {
            "0": "XS",
            "20": "S",
            "50": "M",
            "200": "L",
            "500": "XL",
            "1000": "XXL"
          }

jobs:
  size-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@main # v0.5.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sizes: ${{ inputs.sizes }}
