name: Git commit linter

on:
  workflow_call:

jobs:
  commit-lint-check:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: wagoid/commitlint-github-action@master # v6.2.1
