name: Dokploy deployment

on:
  workflow_call:
    secrets:
      github-token:
        description: Github token
        required: true
      url:
        description: Base URL of Dokploy
        required: true
      token:
        description: Auth token for Dokploy
        required: true
      app-id:
        description: Application ID for Dokploy
        required: true

permissions:
  packages: write
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: start production deployment
        uses: bobheadxi/deployments@main # v1.5.0
        id: production-deployment
        with:
          step: start
          token: ${{ secrets.github-token }}
          env: production
          ref: ${{ github.head_ref }}

      - name: Dokploy deploy
        uses: ITSolve-dev/BackOffice.GitHubActions/.github/actions/dokploy@main
        with:
          url: ${{ secrets.url }}
          token: ${{ secrets.token }}
          app-id: ${{ secrets.app-id }}

      - name: update deployment status
        uses: bobheadxi/deployments@main # v1.5.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.production-deployment.outputs.env }}
          deployment_id: ${{ steps.production-deployment.outputs.deployment_id }}
          ref: ${{ github.head_ref }}
          env_url: ${{ inputs.url }}
