name: Dokploy deployment

on:
  workflow_call:
    inputs:
      project-name:
        description: Project name
        required: true
        type: string
      application-name:
        description: Application name
        required: true
        type: string
      url:
        description: Base URL of Dokploy
        required: true
        type: string
      token:
        description: Auth token for Dokploy
        required: true
        type: string

permissions:
  packages: write
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: start production deployment
        uses: bobheadxi/deployments@main # v1.5.0
        id: production-deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          ref: ${{ github.head_ref }}

      - name: Dokploy deploy
        uses: jmischler72/dokploy-deploy-actions@main
        with:
          PROJECT_NAME: ${{ inputs.project-name }}
          APPLICATION_NAME: ${{ inputs.application-name }}
          DOKPLOY_HOST: ${{ inputs.url }}
          DOKPLOY_TOKEN: ${{ inputs.token }}

      - name: update deployment status
        uses: bobheadxi/deployments@main # v1.5.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.production-deployment.outputs.env }}
          deployment_id: ${{ steps.production-deployment.outputs.deployment_id }}
          ref: ${{ github.head_ref }}
          env_url: ${{ inputs.url }}
