# https://github.com/actions/labeler
# https://github.com/fastapi/fastapi/blob/master/.github/workflows/labeler.yml
name: Pull Request Labeler
on:
  pull_request:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@main
      - uses: actions/labeler@main # v5.0.0
